// Regenerates every app icon from one 16×16 pixel grid.
//
//   node scripts/icons.mjs
//
// The mark is the same stack of kept cards as the OG image, drawn as pixel art
// instead of vectors: a smooth version turned to mush at 16px (the size a tab
// actually shows), while a 16-grid stays sharp there and scales by whole pixels
// everywhere else. Every output is an integer multiple of the grid, padded with
// black — nothing is resampled, so nothing blurs.

import { writeFileSync } from "node:fs";
import sharp from "sharp";

const N = 16;
const C = {
  bg: [0, 0, 0],
  amber: [0xff, 0xb0, 0x00],
  // Amber at 60% / 35% over black, pre-mixed so the back cards stay solid
  // pixels instead of alpha that every renderer blends differently.
  mid: [0x99, 0x6a, 0x00],
  dim: [0x59, 0x3e, 0x00],
};

// ── Paint the grid, back to front ──────────────────────────────────────────
const grid = Array.from({ length: N }, () => Array(N).fill("bg"));

/** A card: border + fill, corner pixels left unpainted so it reads rounded. */
function card(x0, y0, x1, y1, border, fill) {
  for (let y = y0; y <= y1; y++) {
    for (let x = x0; x <= x1; x++) {
      const edgeX = x === x0 || x === x1;
      const edgeY = y === y0 || y === y1;
      if (edgeX && edgeY) continue;
      grid[y][x] = edgeX || edgeY ? border : fill;
    }
  }
}

// The back two are outlines with an opaque black body, so each one hides the
// card behind it — overlapping outlines were most of the old icon's noise.
card(6, 1, 13, 10, "dim", "bg");
card(4, 3, 11, 12, "mid", "bg");
card(2, 5, 9, 14, "amber", "amber");
// A saved entry's lines, cut out of the front card.
for (const [y, x0, x1] of [
  [7, 4, 7],
  [9, 4, 7],
  [11, 4, 6],
]) {
  for (let x = x0; x <= x1; x++) grid[y][x] = "bg";
}

// ── Rasters ────────────────────────────────────────────────────────────────

/**
 * The grid at `unit` px per cell, centred in `cells` cells of black.
 * `rounded` cuts the corners of the black tile (tabs show it on any colour);
 * full-bleed tiles are for platforms that mask the icon themselves.
 */
async function png({ unit, cells = N, rounded = false }) {
  const size = cells * unit;
  const off = ((cells - N) / 2) * unit;
  const buf = Buffer.alloc(size * size * 4);
  const r = rounded ? 3 * unit : 0;
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      const gx = Math.floor((px - off) / unit);
      const gy = Math.floor((py - off) / unit);
      const inArt = gx >= 0 && gx < N && gy >= 0 && gy < N;
      const color = C[inArt ? grid[gy][gx] : "bg"];
      const i = (py * size + px) * 4;
      buf.set(color, i);
      buf[i + 3] = r && outsideCorner(px, py, size, r, unit) ? 0 : 255;
    }
  }
  return sharp(buf, { raw: { width: size, height: size, channels: 4 } })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/** Whole cells outside the rounded corner — stair-stepped, like the art. */
function outsideCorner(px, py, size, r, unit) {
  const cx = Math.floor(px / unit) * unit + unit / 2;
  const cy = Math.floor(py / unit) * unit + unit / 2;
  const dx = cx < r ? r - cx : cx > size - r ? cx - (size - r) : 0;
  const dy = cy < r ? r - cy : cy > size - r ? cy - (size - r) : 0;
  return dx > 0 && dy > 0 && dx * dx + dy * dy > r * r;
}

/** ICO is a directory of embedded PNGs; every browser since IE has read it. */
function ico(entries) {
  const header = Buffer.alloc(6 + 16 * entries.length);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(entries.length, 4);
  let offset = header.length;
  entries.forEach(({ size, data }, i) => {
    const e = 6 + 16 * i;
    header[e] = size;
    header[e + 1] = size;
    header.writeUInt16LE(1, e + 4);
    header.writeUInt16LE(32, e + 6);
    header.writeUInt32LE(data.length, e + 8);
    header.writeUInt32LE(offset, e + 12);
    offset += data.length;
  });
  return Buffer.concat([header, ...entries.map((e) => e.data)]);
}

// ── SVG: one rect per horizontal run, crisp edges ──────────────────────────
function svg() {
  const hex = (c) => "#" + c.map((v) => v.toString(16).padStart(2, "0")).join("");
  const rects = [];
  for (let y = 0; y < N; y++) {
    let x = 0;
    while (x < N) {
      const k = grid[y][x];
      let end = x;
      while (end + 1 < N && grid[y][end + 1] === k) end++;
      if (k !== "bg") {
        rects.push(`<rect x="${x}" y="${y}" width="${end - x + 1}" height="1" fill="${hex(C[k])}"/>`);
      }
      x = end + 1;
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 ${N} ${N}">
  <!-- Generated by scripts/icons.mjs from a 16×16 grid; edit the grid there. -->
  <rect width="${N}" height="${N}" rx="3" fill="#000"/>
  <g shape-rendering="crispEdges">
    ${rects.join("\n    ")}
  </g>
</svg>
`;
}

const out = {
  "app/icon.svg": svg(),
  "app/favicon.ico": ico([
    { size: 16, data: await png({ unit: 1, rounded: true }) },
    { size: 32, data: await png({ unit: 2, rounded: true }) },
    { size: 48, data: await png({ unit: 3, rounded: true }) },
  ]),
  // iOS rounds the corners itself, so these are full-bleed.
  "app/apple-icon.png": await png({ unit: 10, cells: 18 }),
  "public/icon-192.png": await png({ unit: 8, cells: 24 }),
  "public/icon-512.png": await png({ unit: 32 }),
  // Maskable: launchers crop to as little as the centre 80% circle. The
  // farthest lit pixel sits 8.5 cells from centre, so 22 cells (radius 8.8)
  // is the tightest fit — at 23px that's 506, padded to 512 below.
  "public/icon-maskable-512.png": await sharp(await png({ unit: 23, cells: 22 }))
    .extend({ top: 3, bottom: 3, left: 3, right: 3, background: "#000" })
    .png({ compressionLevel: 9 })
    .toBuffer(),
};

for (const [path, data] of Object.entries(out)) {
  writeFileSync(path, data);
  console.log("wrote", path);
}
